apiVersion: gateway.k8s.aws/v1
kind: LoadBalancerConfiguration
metadata:
  name: roboshop-alb
  namespace: roboshop
spec:
  scheme: internet-facing
  ipAddressType: ipv4
  listenerConfigurations:
  - protocolPort: HTTPS:443
    certificates:
    - arn:aws:acm:us-east-1:884057990406:certificate/da01ef73-2cf5-4ea2-a5a9-10d13310947b

# We are going to use ALB, Listener